In [4]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

type(arr)

[1 2 3 4 5]


numpy.ndarray

In [5]:
a = np.array(42) # zero dimension

b = np.array([1,2,3,4,5]) # one dimension

c = np.array([[1,2,3],[4,5,6]]) # two dimension

d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]) # three dimension

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [6]:
arr = np.array([1,2,3,4])
print(arr[2] + arr[3])

7


In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # two dimension

print('5th element on the 2nd row: ', arr[1,4]) # 0 index
print('1st element on the 1st row: ', arr[0,0])
print('5st element on the 1st row: ', arr[0,4])
print('1st element on the 2st row: ', arr[1,0])

5th element on the 2nd row:  10
1st element on the 1st row:  1
5st element on the 1st row:  5
1st element on the 2st row:  6


In [15]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # three dimension

print(arr[0,1,2])
print(arr[1,0,0])
print(arr[1,1,1])
print(arr[1,1,2])


6
7
11
12


In [17]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[-1,-1])
print(arr[-1,-2])

10
9


In [26]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[0:])
print(arr[:4])
print(arr[-3:-1])
print(arr[-1:-2:-3])
print(arr[1:5:2])

[2 3 4 5]
[1 2 3 4 5 6 7]
[1 2 3 4]
[5 6]
[7]
[2 4]


In [36]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # two dimension array

print(arr[1,1:4]) # the comma for it to get 7,8,9
print(arr[0:2, 1:4]) # to get 2,3,4 and 7,8,9

[7 8 9]
[[2 3 4]
 [7 8 9]]


In [37]:
arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [38]:
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [39]:
for x in arr:
    for y in x:
        print(y)
        

1
2
3
4
5
6


In [40]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
